version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: movie-gpt-mongo

    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: moviegpt

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      retries: 5

  redis:
    image: redis:8
    container_name: movie-gpt-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: movie-gpt-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5

  app:
    build: .
    container_name: movie-gpt-app
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/moviegpt
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_URL: amqp://rabbitmq:5672
      JWT_SECRET: supersecretkey
      OPENAI_API_KEY: seu_token_aqui
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
